apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ll2jge6n3-go
  janus-idp.io/tekton: ll2jge6n3-go
  backstage.io/kubernetes-id: ll2jge6n3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ll2jge6n3-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
